name: Sync fork

on:
  schedule:
    - cron: '0 23 * * *'
  workflow_dispatch:
    
jobs:
  sync:
    # if: github.repository_owner != 'LihaoLikeOrangeJuice'
    runs-on: ubuntu-22.04
    
    steps:
      - runs: echo $github.ref_name
      - uses: tgymnich/fork-sync@v1.6.3
        with:
          owner: LihaoLikeOrangeJuice # 上游项目 owner
          head: master # 上游项目需要同步的分支
          base: $github.ref_name # 需要同步的目标分支
