name: Sync fork

on:
  schedule:
    - cron: '0 23 * * *'
  workflow_dispatch:
    
jobs:
  sync:
    runs-on: ubuntu-22.04
    
    steps:
      - uses: tgymnich/fork-sync@v1.6.3
        with:
          owner: LihaoLikeOrangeJuice # 上游项目owner
          head: master # 上游项目分支
          base: master # 目标分支
