name: Sync fork

on:
  schedule:
    - cron: '0 23 * * *'
  workflow_dispatch:
    
jobs:
  sync:
    if: $current_repo_owner != 'LihaoLikeOrangeJuice/clock-in-gzhu'
    runs-on: ubuntu-22.04
    
    steps:
      - uses: tgymnich/fork-sync@v1.6.3
        with:
          owner: LihaoLikeOrangeJuice # 上游项目 owner
          head: master # 上游项目需要同步的分支
          base: master # 需要同步到本项目的目标分支
